### ISSUE TITLE
Set custom font in Toolbar

### ISSUE THREAD

**Issue by aemxn** [madcyph3r/AdvancedMaterialDrawer#11]
Hi, great work you put on improving this library!

I have a question though. Is there a way I can change the toolbar's typeface on fragment change?
I've tried adding a custom textview into Toolbar by `getToolbar()` method, but it still uses default font.

Is there a way I can set this globally so that all fragments are using this custom font on its Toolbar?

**Comment by madcyph3r** [comment]
Use the new lib version 1.0.9.
Here is a new example, how you can set your own custom title.
https://github.com/madcyph3r/AdvancedMaterialDrawer/blob/master/example/src/main/java/de/madcyph3r/example/tools/OwnActionBarFont.java

**Comment by aemxn** [comment]
Man, you are the best! Thank you!
