### ISSUE TITLE
change fragment toolbar and menu

### ISSUE THREAD

**Issue by croccio** [madcyph3r/AdvancedMaterialDrawer#12]
how can i handle the change fragment and show back button? than if first fragment show again menu button? and how can i lock menu?

**Comment by madcyph3r** [comment]
I have implemented it. But for now you must use the current source, if you want to change the button. Will upload a new lib version to binTray later. To lock the drawer, you can use the current binTray version.

To use it, see this example:
https://github.com/madcyph3r/AdvancedMaterialDrawer/blob/master/example/src/main/java/de/madcyph3r/example/tools/ActionBarButtons.java
and
https://github.com/madcyph3r/AdvancedMaterialDrawer/blob/master/example/src/main/java/de/madcyph3r/example/tools/ActionBarButtons/FragmentActionBarButtons.java
