### ISSUE TITLE
window overlay

### ISSUE THREAD

**Issue by croccio** [madcyph3r/AdvancedMaterialDrawer#13]
i cannot set windows overlay property. neither from manifest and neither dynamically

**Comment by madcyph3r** [comment]
Can you give me an example? In another project i used this lib: https://github.com/pingpongboss/StandOut and it works really well.

**Comment by croccio** [comment]
I set overlay mode first in manifest and doesn’t work
than from code editing your library and doesn’t work.
To work around this problem i set animation of toolbar with nine old android and it seems to work, but i would know if there’s a method to use system overlay

**Comment by madcyph3r** [comment]
Can you provide example code please?

**Comment by croccio** [comment]
create an activity and in oncreate(...) method before super.oncreate(...) do this

```
getWindow().requestFeature(Window.FEATURE_ACTIONBAR_OVERLAY) 
```

or this for older android
    supportRequestWindowFeature(WindowCompat.FEATURE_ACTIONBAR_OVERLAY)

not work

than i set it from style and theme apply theme in manifest to the activity.
add to theme this line

```
    <item name="android:windowActionBarOverlay" tools:ignore="NewApi">true</item>
    <item name="windowActionBarOverlay">true</item>
```

**Comment by croccio** [comment]
create an activity and in oncreate(...) method before super.oncreate(...) do this

    getWindow().requestFeature(Window.FEATURE_ACTIONBAR_OVERLAY) 
or this for older android
    supportRequestWindowFeature(WindowCompat.FEATURE_ACTIONBAR_OVERLAY)

not work

than i set it from style and theme apply theme in manifest to the activity.
add to theme this line

        <item name="android:windowActionBarOverlay" tools:ignore="NewApi">true</item>
        <item name="windowActionBarOverlay">true</item>

**Comment by croccio** [comment]
create an activity and in oncreate(...) method before super.oncreate(...) do this

    getWindow().requestFeature(Window.FEATURE_ACTIONBAR_OVERLAY) 
or this for older android
    supportRequestWindowFeature(WindowCompat.FEATURE_ACTIONBAR_OVERLAY)

not work

than i set it from style and theme apply theme in manifest to the activity.
add to theme this line

        <item name="android:windowActionBarOverlay" tools:ignore="NewApi">true</item>
        <item name="windowActionBarOverlay">true</item>

**Comment by madcyph3r** [comment]
I found a solution. Will come in the next update.

**Comment by croccio** [comment]
i make a pull request

**Comment by croccio** [comment]
did you see it?

**Comment by madcyph3r** [comment]
I have merged your request. It's a nice solution.
