### ISSUE TITLE
MaterialSection set to an activity 

### ISSUE THREAD

**Issue by norrisboat** [madcyph3r/AdvancedMaterialDrawer#18]
When I  do this the layout of the activity doesn't show. It displays a blank screen

**Comment by madcyph3r** [comment]
Can you post your code? I don't know what do you mean.
Your Activity must extends from MaterialNavigationDrawer.class

**Comment by norrisboat** [comment]
Intent i = new Intent(Sqllite.this,Third.class);
        Intent sq = new Intent(Sqllite.this,Second.class);  

// menu items
MaterialSection instruction = this.newSection("Instruction", sq , false, menu);
instruction.setTitle("Instruction");
this.newLabel("Label", false, menu);
this.newSection("Section", i, false, menu);
this.setActionBarOverlay(false);

But it can't seem to open the layout file in my second activity.

**Comment by madcyph3r** [comment]
You start a new Activity, there is no layout, until you set it.
For every activity you must set a own menu. If you want the same menu on al activities, then use fragments and not activities.

**Comment by norrisboat** [comment]
OK thanks
