### ISSUE TITLE
Examples

### ISSUE THREAD

**Issue by ghost** [madcyph3r/AdvancedMaterialDrawer#19]
Kinda lost `There are a lot of examples with explanations...` where?

**Comment by madcyph3r** [comment]
https://github.com/madcyph3r/AdvancedMaterialDrawer/tree/master/example/src/main/java/de/madcyph3r/example/example

Here is the source code from the example application.

Here you can get the example app: https://play.google.com/store/apps/details?id=de.madcyph3r.MaterialDrawer , and search for the example you need.

**Comment by ghost** [comment]
thanks
