### ISSUE TITLE
Set Each Section Background Color Individually

### ISSUE THREAD

**Issue by mikescamell** [madcyph3r/AdvancedMaterialDrawer#21]
I'm trying to set each sections colour individually by getting the view and setting the background but it doesn't seem to be working. Any ideas how i could do this?

**Comment by madcyph3r** [comment]
To set the section color, you must get the view and call setTextColor(), after the init method.

``` JAVA
section.getText().setTextColor(textColor);

// for background:
section.getText().setBackgroundColor(color);
```

Important is, that you use the after init method for this. So you can be sure that nothing is overwritten..

**Comment by mikescamell** [comment]
Isn't that just to set the colour of the text of each section? I'd like to set the background of each section individually.

**Comment by madcyph3r** [comment]
See my edit in the second post.
Maybe it's easier, if you add a new constructor in the MaterialSection.java, there you can set colorUnpressed and colorSelected. Or setter methods.

**Comment by mikescamell** [comment]
Thank you.
