### ISSUE TITLE
How to use with multiple activities

### ISSUE THREAD

**Issue by thevirus20** [madcyph3r/AdvancedMaterialDrawer#24]
Hi,
First of all thanks for this useful library with ripple support on lower android version.

I am trying to include this library as 2 level navigation with using `BaseActivity`.

What I have done is:
1. Created a `BaseActivity` to include all code that you have given in your sample code.
2. `MainActivity` extends this base activity and I get the drawer as expected with first section fragment loaded(Wiki on neokree repo suggest that first section should should always be fragment, is there a alternative?)

What I have to do is:
1. I have another section which is intent and starts a new `SecondActivity`. Is this possible to make this section as selected when `SecondActivity` is launched(Currently no section is selected when `SecondActivity` is launched).
2. I also get a null pointer exception on `DrawerToggle` while setting a back arrow instead of hamburger in `SecondActivity`. I followed same step as you mentioned in issue #16, but didn't help.

How can I achieve this type of navigation drawer across all activity (like Gmail does, loading a particular email  has Inbox section highlighted, maybe they are using fragment) . Is this possible with Activity or I have to use fragment everywhere to achieve this?

Please help.
By the way please add DummyActivity in your example's manifest.xml, as it causes exception.
Thanks.

**Comment by madcyph3r** [comment]
In this library the first section must not be a fragment. It will load the first fragment it finds or you can defined the start section. Or you set an custom start fragment.

If you want to select the section with an activity, do following:

``` JAVA
// make an section , without an intent and add an on click listener

yourSection.setOnClickListener(new MaterialSectionOnClickListener() {
            @Override
            public void onClick(MaterialSection section, View view) {
                drawer.getCurrentSection().unselect();
                section.select();

                // here comes your intent, to start the new activity.
           }
        });
```

for your drawerToggle problem:

``` JAVA
// use the after init method, not the init method.

    @Override
    public void afterInit(Bundle savedInstanceState) {
        // shows a back button, instead of the drawer icon
        drawer.showActionBarMenuIcon(MaterialNavigationDrawer.ActionBarMenuItem.BACK);
    }
```

and thank you for your hint with the dummyActivity.

**Comment by thevirus20** [comment]
Hi,
Thanks for your quick reply.
`afterInit()` method does work but Selecting the section doesn't work with the listener for `SecondActivity`, and I found one more thing that selecting the same section(which launches this activity) again create new Intent. similarly selecting that again same activity is lauched. 
And Now if I press back(again & again) I get drawer open with second section selected, till I get to first section fragment.

Also can you please give any example on how can I avoid using first fragment? What will happen if my first section is also an activity?

In your example app, `SetCustomFragmentActivity` has `this.setCustomFragment();` which doesn't loads the instruction fragment please check.

I just simply want to replace my app navigation which has multiple activities (not fragments) with the NavigationDrawer, that's why I wanted the drawer section to have activity instead of fragment(with proper selection) if this can be achieved using your lib? otherwise I have convert everything to fragment.

Please let me know if that is possible and please give update on SectionListener that you suggested me as it doesn't work when Activity is lauched but does work when back is pressed .

Hope you understand what I am asking.
Thanks.

**Comment by madcyph3r** [comment]
I have correct the example. Now the custom fragment loads ;).
See here:
https://github.com/madcyph3r/AdvancedMaterialDrawer/blob/2dd00a02f395ddd33a057c91f7ccd5fd035ee472/example/src/main/java/de/madcyph3r/example/example/functionally/SetCustomFragmentActivity.java

So you can set a custom fragment on every activity load. Your menu must not have an fragment section, but then you should use a custom fragment on start.

And set the onClick listener like this:

``` JAVA
        // global var. Save the latest activitySection
        private final MaterialSection tmpSection = null;

        yourSection.setOnClickListener(new MaterialSectionOnClickListener() {
            @Override
            public void onClick(MaterialSection section, View view) {
                if(drawer.getCurrentSection() != null)
                    drawer.getCurrentSection().unselect();

                if(tmpSection == null && tmpSection != section) {
                    tmpSection = section;
                    section.select();

                    // if you use on every activity the same menu, then send the selected section position
                    int pos = drawer.getCurrentMenu().getSectionPosition();

                    // start activity
                    Intent myIntent = new Intent(drawer, B.class);
                    myIntent.putExtra("selPos", pos);
                    drawer.startActivity(myIntent);


                  // on the new activity do this in the after init method and you set the custom fragment:
                  // Intent intent= getIntent();
                  // Bundle b = intent.getExtras();
                  // if(b!=null)
                  // {
                  // int pos =(int) b.get("selPos");
                  // drawer.getCurrentMenu().getSection(pos).select();
                  //}

                }

            }
        });
```

If you press back button use the no close prev actitivty example. see here:
https://github.com/madcyph3r/AdvancedMaterialDrawer/blob/2dd00a02f395ddd33a057c91f7ccd5fd035ee472/example/src/main/java/de/madcyph3r/example/example/functionally/noClosePrevDrawerActivity/NoCloseActivity.java

Important: this is a really bad practice. Better you use fragments, it's not really difficult. Use only a new Activity, if you don't need the menu or you need a new drawer menu with a different context.
And it's complicated, to send every time the menu position. And it creates every time a new menu, this makes your app slower and you need more ram, because every activity is in your ram, if you don't call finish() on activity start.

Ram Example:
1 Activity and 5 Fragments:
in your ram is 1 activity with the drawer. The drawer creates on activity start, only one time.
Only the fragments will changed.

5 Activities, every has 1 Frament (custom Fragment):
every new activity start creates new own menu. (it's the same menu, but different objects) 
so you have 5 activities and 5 menu objects in your ram. 

You see, you need more ram and you create on every activity start a new menu. Your app get's slower.

**Comment by thevirus20** [comment]
OK Thanks.

But How to select the correct section after activity loads I was not able to do that with your Listener.
Can you please check that how can I select a section when activity is lauched (and suppose custom fragment is loaded)?

What I want is like Gmail. I have inbox activity which loads email(inbox section is selected) and then clicking individual email opens new activity which has different content but must have the drawer and inbox selected.

How can I achieve this with Activity?Or is it possible to do with activity or Fragment is must here?

**Comment by madcyph3r** [comment]
For this case you use normally fragments. If i have time today, i kan make a small example for you with the activity. But it's easier, if you use fragments.

See here, the wiki from neokree explains, how do you convert your activity to fragment.
https://github.com/neokree/MaterialNavigationDrawer/wiki/Moving-to-MaterialNavigationDrawer

It's very easy.

**Comment by thevirus20** [comment]
Yes I actually started to convert them in Fragments(because clicking same section again launches activity as I said above). I was going to implement MasterChild Fragment which neokree has done, but then I got link to this lib I tested it on API8 device it worked so I changed my mind to use this. But I still need master child type navigation with drawer every where. As you have advanced his library I think ,can still use that Masterchild fragment.

Lets see If I am able to make it like Gmail does.

Thanks for your support.

**Comment by thevirus20** [comment]
You can also Include a sample with Masterchild fragment in your example  so that it will be helpful for someone working with multilevel navigation.

**Comment by madcyph3r** [comment]
Okay, i will add an master child example. If you can't get it to work, the  write here. Then i will make an example this evening. Its a little different from neokree.

**Comment by madcyph3r** [comment]
Here i have made an master child example.

See here: https://github.com/madcyph3r/AdvancedMaterialDrawer/blob/master/example/src/main/java/de/madcyph3r/example/example/functionally/MasterChildNavActivity.java

and here: https://github.com/madcyph3r/AdvancedMaterialDrawer/tree/master/example/src/main/java/de/madcyph3r/example/example/functionally/masterChildNavActivity

have fun with it ;).
