### ISSUE TITLE
How to keep ActionBar when i start a new activity ?

### ISSUE THREAD

**Issue by byMohamedali** [madcyph3r/AdvancedMaterialDrawer#25]
Hi, first thanks for this very USEFUL library,

I have just one problem, when i want to start another activity, i don't know how to keep action bar.

// my home activity with navigation drawer
public class MainActivity extends MaterialNavigationDrawer 
....
startActivity(intent);
....

// my second activity
public class GainActivity extends ActionBarActivity

I hope i was clear :)
Thank you.

**Comment by madcyph3r** [comment]
You must set your own toolbar, see here:
http://android-developers.blogspot.de/2014/10/appcompat-v21-material-design-for-pre.html

or you extends from MaterialNavigationDrawer
and then set 
drawer.setDrawerLockMode(DrawerLayout.LOCK_MODE_LOCKED_CLOSED);
in the after init method, so the drawer will not be shown, but you have the toolbar from the drawer.

**Comment by byMohamedali** [comment]
Thank you :)
