### ISSUE TITLE
add section dynamically

### ISSUE THREAD

**Issue by croccio** [madcyph3r/AdvancedMaterialDrawer#3]
how can i add section dynamically? is it possible?

**Comment by croccio** [comment]
please make loadMenu(boolean value) public so we can refresh drawer menu

**Comment by croccio** [comment]
@madcyph3r if you would i can do a fork and than a pull request

**Comment by madcyph3r** [comment]
I have make a code change, to reload the menu. It's not a good idea, to use the original loadMenu() Method, to do that. See the latest commit.

**Comment by croccio** [comment]
@madcyph3r can you see my pull request? ok for refresh menu, but i've done another commit to handle close activity drawer without override onClickListener of section. Thank you

**Comment by croccio** [comment]
@madcyph3r i've implemeted a method to realoaDmenu without call method too but with a flag in newSection/label/devider. can you implement something like that? it will be very useful

**Comment by croccio** [comment]
@madcyph3r new version 1.0.7, isn't on repo? android studio tell me that there isn't 1.0.7 version. thank you

**Comment by madcyph3r** [comment]
For now you must use the source. Tomorrow i will add it on the repo. Before, i want to make some changes. And i will add the flag option to reload the menu, so you don't must call the reload method, if you don't want this. 

I have merged your other commit manually.
Thank you for your help.
