### ISSUE TITLE
Start Fragment from Another Fragment

### ISSUE THREAD

**Issue by patelakshay13890** [madcyph3r/AdvancedMaterialDrawer#31]
How can I Start Fragment from Another Fragment ?
And Current Fragment is in Material Drawer & New Fragment to be replaced is not in the Material Drawer..So how can I start New Fragment on Button Click that is in Current Fragment ?

**Comment by aemxn** [comment]
Please check this example [Master Child Navigation](https://github.com/madcyph3r/AdvancedMaterialDrawer/tree/master/example/src/main/java/de/madcyph3r/example/example/functionally/masterChildNavActivity)

**Comment by patelakshay13890** [comment]
But I on BackPressed Button in Child I don't want New Instance of
MasterFragmenent instead MasterFragment Old Content I want..
How can I achieve this ??

**Comment by madcyph3r** [comment]
For this, look here. You can set your own back action.

https://github.com/madcyph3r/AdvancedMaterialDrawer/blob/master/example/src/main/java/de/madcyph3r/example/example/backPattern/BackPatternCustomActivity.java

Combinate the MasterChild- and Custom BackPattern-Example. ;).
