### ISSUE TITLE
In New Latest Lib. getting Error

### ISSUE THREAD

**Issue by patelakshay13890** [madcyph3r/AdvancedMaterialDrawer#32]
I am getting error in importing latest lib. 
Error is shown in below image..
What is the solution ??
![wrror](https://cloud.githubusercontent.com/assets/6092323/7290962/cd13697c-e9a5-11e4-8df4-13578494c2dd.png)

**Comment by madcyph3r** [comment]
Should be fixed now. Get the latest git.
