### ISSUE TITLE
jerky from selecting items in the drawer

### ISSUE THREAD

**Issue by jjhesk** [madcyph3r/AdvancedMaterialDrawer#33]
since there is heavy loading from the layout and binding layout within the fragment. I want to ask for a better solution to transit different fragments in the layout. accordingly [article](http://stackoverflow.com/questions/18343018/optimizing-drawer-and-activity-launching-speed). is there anyway to implement that into the code base?

**Comment by madcyph3r** [comment]
I have added it. Use the latest git. The next week, i will push a new release.
