### ISSUE TITLE
Check weather Drawer is open

### ISSUE THREAD

**Issue by patelakshay13890** [madcyph3r/AdvancedMaterialDrawer#34]
How to Check weather Drawer is open or not ??
And How to toggle the Drawer ??

**Comment by thevirus20** [comment]
You can add this method

``` java
public boolean isDrawerOpen(){
    return drawerLayout.isDrawerOpen(drawerViewGroup);
}
```

To toggle , can add a method like this.

``` java
public void toggleDrawer(){
    if(isDrawerOpen())
        closeDrawer();
    else
        openDrawer();
}
```

**Comment by patelakshay13890** [comment]
But there is no method such as  drawerLayout.isDrawerOpen(drawerViewGroup)
!!!

**Comment by thevirus20** [comment]
You need to add those two method in `MaterialNavigationDrawer.java` then use it in activity extending Drawer like this,

``` java
drawer.toggle();
```

Are you using this lib as source or using maven?

**Comment by madcyph3r** [comment]
I will add the methods from thevirus20. After this, i will relase a new lib version. The new version will have the methods you neeeded. For now see the answers from thevirus20, you must add the methods yourself.

**Comment by madcyph3r** [comment]
I have added it. Use the latest git. The next week, i will push a new release.
