### ISSUE TITLE
How can I Replace Fragment ?

### ISSUE THREAD

**Issue by patelakshay13890** [madcyph3r/AdvancedMaterialDrawer#39]
How can I Replace Fragment from Curr. Fragment but not like Master Child Navigation , want to replace as in the done in Section Selection in DrawerActivity..??

**Comment by madcyph3r** [comment]
Call only:

``` JAVA
drawer.setCustomFragment(new youtFragment(), "Your Fragment Title");
```

in your function. That's all.

**Comment by patelakshay13890** [comment]
How can I use same Menu by Inflating in Drawer Activity ??
By doing son I cannot open Drawer..

**Comment by patelakshay13890** [comment]
Can we have Drawer on both sides ???
