### ISSUE TITLE
Use Same Menu for all Fragment

### ISSUE THREAD

**Issue by patelakshay13890** [madcyph3r/AdvancedMaterialDrawer#40]
How can I have same Menu in all fragments ??
If i use OnCreateMenu in DrawerActivity then I cannot access the Drawer, so how can I achieve this ??

**Comment by madcyph3r** [comment]
You mean onCreateOptionsMenu() , or?

For an optionsMenu, look here:
https://github.com/madcyph3r/AdvancedMaterialDrawer/blob/master/example/src/main/java/de/madcyph3r/example/example/functionally/ActionBarButtonsActivity.java

**Comment by patelakshay13890** [comment]
But instead of Having Dynamic Menu Item I want to inflate from menu in res
 & have onOptionsItemSelected Method for the same, so how can I do this ??
& How Can we have same Title for the application & Change Icon for drawer
when it's open & Closed ??

**Comment by madcyph3r** [comment]
Then inflate the menu like this:

``` JAVA
@Override
@TargetApi(11)
@Override
public boolean onCreateOptionsMenu(Menu menu)
{
    MenuInflater inflater = getMenuInflater();
    inflater.inflate(R.menu.mainmenu, menu);

   // on click listener (same as onOptionsItemSelected) or use onOptionsItemSelected(MenuItem item), but don't forget to call the super method. (return super.onOptionsItemSelected(item);)

    return true;
}
```

To have the same title in all fragments, call the setFragmentTitle() for every section, like this:

``` JAVA
MaterialSection section = this.newSection("Section 1", new FragmentDummy(), false, menu);
section.setFragmentTitle("your title");
// do this for all your sections.
```

Which icon do you want to change? The menu icon is not visible, if the drawer open.

**Comment by patelakshay13890** [comment]
Yes I want to change Menu Icon & I m using Theme Below ToolBar so how can I
achieve this ??

**Comment by madcyph3r** [comment]
To change the icon do this:

``` JAVA
if(getActionBarToggle() != null)
                    getActionBarToggle().setDrawerIndicatorEnabled(false);
            getSupportActionBar().setHomeButtonEnabled(true);
            getSupportActionBar().setDisplayHomeAsUpEnabled(true);
            // set the icon
            getSupportActionBar().setHomeAsUpIndicator(Drawable indicator)
            getSupportActionBar().invalidateOptionsMenu();
```

For all methods see here: https://developer.android.com/reference/android/support/v7/app/ActionBar.html

**Comment by madcyph3r** [comment]
I close this issue for now. If the problem not fixed, make a new thread please.
