### ISSUE TITLE
Small glitch when opening new Fragment

### ISSUE THREAD

**Issue by AlexandruDev** [madcyph3r/AdvancedMaterialDrawer#41]
I have 6 sections ( 6 fragments ) inside the Drawer and the problem is that when I press on a section there's a small glitch. I just don't like the fact that the drawer executes 2 operations in the same time ( it closes the drawer and it opens the new fragment in the same time ) --> which causes that glitch. 
How can I avoid this?

I was thinking to implement a handler ( even if it's not a good practice ) but I can't get it done.

Or maybe someone can come up with a better solution, thanks!

**Comment by madcyph3r** [comment]
Clone this repo and search for 200 in MaterialNavigationDrawer.java . Change this value to a higher nummer. Try 250 or 300.
