### ISSUE TITLE
Switcher menu item

### ISSUE THREAD

**Issue by skynetua** [madcyph3r/AdvancedMaterialDrawer#43]
Could you please add Switcher menu item like in google play music app? Or maybe there are some suggestions so I can do it easilly?

Thanks!

**Comment by madcyph3r** [comment]
Can you post some screenshots pls?

**Comment by skynetua** [comment]
I tried to do it myself however I have few issues and don't know how to fix them. 
It looks like:
![quickmemo _2015-05-12-12-02-30 1](https://cloud.githubusercontent.com/assets/3670941/7583580/49fe5a8e-f89f-11e4-84b7-c667d2b7d7a1.png)

**Comment by madcyph3r** [comment]
Ok, thank you. I think, i will a custom section, so you can make your own design.

**Comment by madcyph3r** [comment]
I have added a custom section now. Now you can do it :). See the allMenu example in the example app (code).
