### ISSUE TITLE
Master Child Navigation

### ISSUE THREAD

**Issue by patelakshay13890** [madcyph3r/AdvancedMaterialDrawer#45]
How can I use Master Child Navigation up to multilevel ??
Bcoz of multi-level navigation does not work properly..

**Comment by madcyph3r** [comment]
I don't know there the problem is.

``` JAVA
drawer.setCustomFragment(new ChildFragment(), "Child Title");
```

with this function, you can start unlimit fragments and so you can make a master child navigation.

**Comment by patelakshay13890** [comment]
How can have Multi drawer ??
I do need this badly..

**Comment by madcyph3r** [comment]
If you want a new drawer, start a new activity and add a new drawer. On backPress you go back to the old activity. Don't call finish on activity start and all is good ;), you have your multi drawer.

``` JAVA
// Don't close drawer activity
    @Override
    public boolean finishActivityOnNewIntent() {
        return false;
    }
```

Override this method in your activity.

For more see here:
https://github.com/madcyph3r/AdvancedMaterialDrawer/blob/master/example/src/main/java/de/madcyph3r/example/example/functionally/NoClosePrevDrawerActivity_Activity.java

A new drawer must be added in a new activity. If the drawer no changed, you use fragments.

Alternative:
Change the menu on a click, like here:
https://github.com/madcyph3r/AdvancedMaterialDrawer/issues/44

**Comment by patelakshay13890** [comment]
How can we have  Multi Drawer using Code not by using Intent ??

**Comment by madcyph3r** [comment]
This is not possible. There is no function, to change the drawer.

**Comment by patelakshay13890** [comment]
okay...
I need that

**Comment by madcyph3r** [comment]
Why you can't make a new activity? Or change the menu, without to load a new activity?

**Comment by skynetua** [comment]
Is there ability to navigate from top level child to previous child by back button? Should I implement custom back pattern or there are some ease way?

**Comment by madcyph3r** [comment]
I think this is, what you want:
https://github.com/madcyph3r/AdvancedMaterialDrawer/blob/master/example/src/main/java/de/madcyph3r/example/example/backPattern/BackPatternLastSectionActivity.java

Use MaterialNavigationDrawer.BACKPATTERN_LAST_SECTION for your back pattern. Otherwise you must implement your own back pattern
