### ISSUE TITLE
divider seems not working

### ISSUE THREAD

**Issue by jjhesk** [madcyph3r/AdvancedMaterialDrawer#46]
i used the code like so:

``` java

        newDevisor(menu);
        newSection("Fashion", listpage.newInstance(fashion()), false, menu);
        newDevisor(menu);
```

it doesnt work as expected.

**Comment by madcyph3r** [comment]
Can you try to edit the theme.
Please try the "MyOwnTheme" from here:
https://github.com/madcyph3r/AdvancedMaterialDrawer/blob/master/example/src/main/res/values/styles.xml

Can you see the divider in the example app?

**Comment by jjhesk** [comment]
and which attribute should i try to edit? MyOwnTheme

**Comment by madcyph3r** [comment]
Sorry for the late response. I will post it tomorrow, which attribute you must change. Have you tried the example apk?

**Comment by jjhesk** [comment]
I think the function didnt work and it is because the linearlayout didnt work properly on 5.0.

**Comment by jjhesk** [comment]
I am still working on my [pull](https://github.com/madcyph3r/AdvancedMaterialDrawer/pull/48) it seems the only thing is the devision bar. Otherwise it will be perfect. I have also tested your demo app and the devision was not showing on the visual.

**Comment by jjhesk** [comment]
what is the different `addDevisor` and `addDevisorBottom`?
They seems the same to in the code.

**Comment by madcyph3r** [comment]
I will look into it. The next weekend.

addDevisorBottom adds an divider to the bottom section. But if i remember me right, there was a problem with it. So there is no different now.

**Comment by jjhesk** [comment]
I think i merged already. I will make another pull again.

**Comment by madcyph3r** [comment]
I will check it with your latest pull. :) Thank you for your code.

**Comment by madcyph3r** [comment]
I think i have found the problem. With the next commit, it should be gone.
