### ISSUE TITLE
Status bar (top bar) alweys is darken

### ISSUE THREAD

**Issue by b3stia** [madcyph3r/AdvancedMaterialDrawer#47]
Hi,
top bar alweys is dark (like have extra layer with #66000000"),  even with : 
< item name=" autoDarkStatusBar ">false< /item >

to be shure i also change:
autoDarkStatusbar = false; 
in init, but effect stay, how to disable it?

**Comment by b3stia** [comment]
Ok, i have found solution, i library in "values-v21/themes" i styles was:
< item name="android:windowTranslucentStatus" > true < /item >
after change to:
< item name="android:windowTranslucentStatus" > false< /item >
application look like it supposted. (top bar have primary_dark )

**Comment by madcyph3r** [comment]
On which android version do you have tested it?

**Comment by b3stia** [comment]
tested on:
LG G3 - android 5.0.0
Nexus 4 - 5.0.2

on both versions i had this issues
