### ISSUE TITLE
Head item don't show the title and subtitle

### ISSUE THREAD

**Issue by Polomsi** [madcyph3r/AdvancedMaterialDrawer#50]
Hi madcyph3r!
I'm using your repositorie for an app but I have a problem with the head item: I have copied your head item example but in my app it doesn't show the "Head title" and "Head Subtitle", only the "Head Image"... and I don't know what can I do for fix this...
Have you any idea about fix this problem?

**Comment by madcyph3r** [comment]
Which version do you use?

**Comment by Polomsi** [comment]
I am using the 1.1.0 version.

**Comment by madcyph3r** [comment]
have you tried the newest version. What is your android version?

**Comment by Polomsi** [comment]
My Android version is Lollipop 5.0.2, but I tried with another smartphone with Jellybean 4.2.2 and it neither worked

**Comment by madcyph3r** [comment]
Worked it with the example app? Dou you use a default theme?

**Comment by madcyph3r** [comment]
On every test, the libarary shows me the title and subtitle. It must be in your code.

**Comment by madcyph3r** [comment]
You get the failure, if you use your own style and you doesn't extends from a material style.
