### ISSUE TITLE
Latest Android updates causing problems?

### ISSUE THREAD

**Issue by Morgazmo** [madcyph3r/AdvancedMaterialDrawer#51]
I'm not entirely sure of the cause, but I'm quietly confident recent changes in Android have caused a conflict with your library:

```
~PathToMyProject\app\build\intermediates\exploded-aar\de.madcyph3r\materialDrawer\1.1.3\res\values\values.xml
Error:(2) Attribute "rippleColor" has already been defined
```

I'm pretty sure it's adding this new dependency which is causing the problem since it seems to compile without it:

```
compile 'com.android.support:design:22.2.0'
```

**Comment by jjhesk** [comment]
just need use the new prefix.

**Comment by madcyph3r** [comment]
normally it's renamed to sectionRippleColor. I will check this.

**Comment by madcyph3r** [comment]
Use the latest version and make a cleanup, Now all should be okay.
