### ISSUE TITLE
Failed to resolve.

### ISSUE THREAD

**Issue by HanderWei** [madcyph3r/AdvancedMaterialDrawer#54]
I add

```
repositories {
    maven { url 'http://dl.bintray.com/madcyph3r/maven/' }
}

dependencies {
    compile 'de.madcyph3r:materialDrawer:1.1.3@aar'
}
```

in  **build.gradle**.  But it return `Failed to resolve: de.madcyph3r:materialDrawer:1.1.3`

Any help will be appreciated.

**Comment by madcyph3r** [comment]
The library is up. Have you add it to the right xml? Maybe there was a problem with the internet connection. Have you tried it again?

**Comment by HanderWei** [comment]
@madcyph3r you are right. It was a internet connection problem.
Thanks a lot.
