### ISSUE TITLE
DialogFragment on click section issue

### ISSUE THREAD

**Issue by aemxn** [madcyph3r/AdvancedMaterialDrawer#56]
I'm passing a DialogFragment into newSection in my drawer. In order for the dialog event to show, it needs to use `.show()` method. The problem with this is every time my drawer started, it will automatically trigger the event without having me to click on the section.

Here is the code for clarification:

```
        FragmentManager fm = getSupportFragmentManager();
        FragmentLogoutDialog fragmentLogoutDialog = new FragmentLogoutDialog();
        fragmentLogoutDialog.show(fm, "logout_dialog_fragment");
        this.newSection(getString(R.string.section_bottom_logout), fragmentLogoutDialog, true, menu);
```

Anything else besides DialogFragment is fine with this. How do I make DialogFragment trigger only when I click on the section? Or is there something I missed?

Thanks

**Comment by aemxn** [comment]
I resolved it by passing an Activity instead.

However, is it possible if DialogFragment can be passed into newSection? Perhaps it can increase the flexibility of the drawer in the future.

**Comment by madcyph3r** [comment]
For this you need a own onClickListener for your section. Check the example app.
