### ISSUE TITLE
Account photo is changed to color

### ISSUE THREAD

**Issue by b3stia** [madcyph3r/AdvancedMaterialDrawer#60]
Hi, i have an issues with photos of account items, if i have more than three accounts (head items) and them go to list, library change photo to pink color like below:

![screenshot_2015-07-09-13-19-14](https://cloud.githubusercontent.com/assets/4069408/8594084/ec379ec0-263d-11e5-9c7c-5d19cc958ad3.png)
![screenshot_2015-07-09-13-19-25](https://cloud.githubusercontent.com/assets/4069408/8594086/ed111452-263d-11e5-83cd-06307ab1f2a8.png)

**Comment by madcyph3r** [comment]
I must look into it. There is no solution yet. I hope i can find a solution soon.

**Comment by b3stia** [comment]
thx!
i am looking for solution from 2 days, all bitmap are recycle properly

**Comment by b3stia** [comment]
to make sure that png isn't a problem i use TextDrawable but now only letter change color:
![screenshot_2015-07-09-15-14-41](https://cloud.githubusercontent.com/assets/4069408/8596098/8c9ee49a-264d-11e5-9bf2-fd9911812ba3.png)
![screenshot_2015-07-09-15-14-51](https://cloud.githubusercontent.com/assets/4069408/8596100/8e5966fc-264d-11e5-9cd0-142772d3d557.png)

so now i am completly confused

**Comment by madcyph3r** [comment]
Which lib version do you use?

**Comment by b3stia** [comment]
versionCode 13
versionName "1.1.1"

**Comment by madcyph3r** [comment]
Can you try version 1.1.3. Because the example app hasen't this problem. May you can send me your code, then it's easier to debug it for me.

**Comment by b3stia** [comment]
ok after check version 1.1.3 i will answer U

**Comment by b3stia** [comment]
ok after implement 1.1.3 and implement all my changes all work proper. Thans for R time and sorry for a problem i should did it at the begging, u have star from me :+1:

**Comment by madcyph3r** [comment]
Nice to hear, that your problem is solved.
