### ISSUE TITLE
Toolbar cut off

### ISSUE THREAD

**Issue by aemxn** [madcyph3r/AdvancedMaterialDrawer#64]
As per title, please refer to my screenshot below. I'm not really sure what is causing this.

It happens after I put `<item name="android:fitsSystemWindows">true</item>` into my `styles.xml` to move Toolbar below status bar.

**styles.xml**

```
<style name="AppTheme.Base" parent="MaterialNavigationDrawerTheme.Light">
    <item name="android:windowNoTitle">true</item>
    <item name="windowActionBar">false</item>
    <item name="android:fitsSystemWindows">true</item>

    <item name="colorPrimary">@color/primary</item>
    <item name="colorPrimaryDark">@color/primary_dark</item>
    <item name="colorAccent">@color/accent</item>
</style>
```

Screenshot 1: With primary color set

[![weird](http://i.stack.imgur.com/zw1Zn.jpg)](http://i.stack.imgur.com/zw1Zn.jpg)

Screenshot 2: Without any color set. Notice there is some additional status bar being added here. Not sure how it got there. Any solution to this?

[![enter image description here](http://i.stack.imgur.com/4nSyi.jpg)](http://i.stack.imgur.com/4nSyi.jpg)

**Comment by madcyph3r** [comment]
Add this to your layout at the first position: 

``` java
<View 
         android:id="@+id/overlayView" 
         android:layout_height="?attr/actionBarSize" 
         android:layout_width="match_parent" 
         android:layout_below="@+id/statusBar" /> 
```

See here: https://github.com/madcyph3r/AdvancedMaterialDrawer/blob/master/materialDrawer/src/main/res/layout/activity_material_navigation_drawer_below_toolbar.xml

**Comment by aemxn** [comment]
Btw, I'm using the drawer with Image Header.

Where do I set those? As I know, my MainActivity doesn't need any layout to be inflated as it extends MaterialNavImageActivity. From what I see, this activity is set to `activity_material_navigation_drawer_customheader.xml` which already has that snippet of code.

**Comment by madcyph3r** [comment]
Have you set the right style in your AndroidManifest.xml? Like here https://github.com/madcyph3r/AdvancedMaterialDrawer/blob/master/example/src/main/AndroidManifest.xml

**Comment by aemxn** [comment]
This is how my Manifest look like:

```
<application
    android:allowBackup="true"
    android:icon="@mipmap/ic_launcher"
    android:label="@string/app_name"
    android:theme="@style/AppTheme">
```

In AppTheme,

```
<style name="AppTheme" parent="AppTheme.Base"/>

<!-- Base application theme. -->
<style name="AppTheme.Base" parent="MaterialNavigationDrawerTheme.Light">
    <item name="android:fitsSystemWindows">false</item>
    <item name="colorPrimary">@color/primary</item>
    <item name="colorPrimaryDark">@color/primary_dark</item>
    <item name="colorAccent">@color/accent</item>
</style>
```

Any idea why this issue still persist?

**Comment by aemxn** [comment]
I've fixed this issue by modifying lib's `activity_material_navigation_drawer_customheader.xml` file. Will PR the fix if necessary.

Thanks!

**Comment by madcyph3r** [comment]
Yes please. So i can check this.
