### ISSUE TITLE
app:theme is now deprecated. Please move to using android:theme instead.

### ISSUE THREAD

**Issue by diogo10** [madcyph3r/AdvancedMaterialDrawer#66]
Hello guys...I just add the library and start get this message in my logcat...the apps keep work normal

```
I/AppCompatViewInflater﹕ app:theme is now deprecated. Please move to using android:theme instead.
```

I saw in some stackoverflow that it is because of Toolbar...I would like let you know that. Thanks.

**Comment by madcyph3r** [comment]
Thank you. I will change it, as soon as i can.
