### ISSUE TITLE
how to change drawer icon?

### ISSUE THREAD

**Issue by sagarmaiyad** [madcyph3r/AdvancedMaterialDrawer#70]
i want to change drawer icon ( hamburger icon).. how can i do that.?

**Comment by madcyph3r** [comment]
https://github.com/madcyph3r/AdvancedMaterialDrawer/blob/master/example/src/main/java/de/madcyph3r/example/example/functionally/actionBarButtonsActivity/FragmentActionBarButtons.java

see here. this is an example, to change it
