### ISSUE TITLE
PreferenceFragment support

### ISSUE THREAD

**Issue by aemxn** [madcyph3r/AdvancedMaterialDrawer#72]
I couldn't add a PreferenceFragment to the drawer as there is no Support Lib v4 for it.

Is there a fix or work around for this issue? Or am I missing something...

Thanks

**Comment by aemxn** [comment]
It's okay. I'll fire up a new Activity intent for this purpose :)

**Comment by gruessung** [comment]
```
compile 'com.github.machinarius:preferencefragment:0.1.1'
```

work's fine :)
