### ISSUE TITLE
failed to resolve

### ISSUE THREAD

**Issue by guphy** [madcyph3r/AdvancedMaterialDrawer#73]
i'm new in android studio.
i want to try and learn this material drawer, and i get an error message.

failed to resolve com.github.madcyph3r:AdvancedMaterialDrawer:2.0.0
what i'm missing?

sorry for my bad english.
thanks for you attention.

**Comment by madcyph3r** [comment]
Hello. See the readme and the gradle Commando with the explination. Or See thevgrasle files in the example project. They have all needed commands.

**Comment by guphy** [comment]
its solve.thanks you so much
