### ISSUE TITLE
enanhchement - ripple effect

### ISSUE THREAD

**Issue by croccio** [madcyph3r/AdvancedMaterialDrawer#8]
if you would to make more beautiful you can implement ripple effect on section pressed

**Comment by madcyph3r** [comment]
it's on the to do list.

**Comment by madcyph3r** [comment]
See the latest release. Ripple is now included.

**Comment by croccio** [comment]
i get this error after update. with old version is working

Error:Execution failed for task ':app:dexDebug'.

> com.android.ide.common.internal.LoggedErrorException: Failed to run command:
>     /Applications/Android Studio.app/sdk/build-tools/21.1.2/dx --dex --no-optimize --output /Users/antonioscardigno/Downloads/QUI-Android5/app/build/intermediates/dex/debug --input-list=/Users/antonioscardigno/Downloads/QUI-Android5/app/build/intermediates/tmp/dex/debug/inputList.txt
>   Error Code:
>     2
>   Output:
>     UNEXPECTED TOP-LEVEL EXCEPTION:
>     com.android.dex.DexException: Multiple dex files define Lcom/nineoldandroids/animation/Animator$AnimatorListener;
>         at com.android.dx.merge.DexMerger.readSortableTypes(DexMerger.java:596)
>         at com.android.dx.merge.DexMerger.getSortedTypes(DexMerger.java:554)
>         at com.android.dx.merge.DexMerger.mergeClassDefs(DexMerger.java:535)
>         at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:171)
>         at com.android.dx.merge.DexMerger.merge(DexMerger.java:189)
>         at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:454)
>         at com.android.dx.command.dexer.Main.runMonoDex(Main.java:303)
>         at com.android.dx.command.dexer.Main.run(Main.java:246)
>         at com.android.dx.command.dexer.Main.main(Main.java:215)
>         at com.android.dx.command.Main.main(Main.java:106)

**Comment by croccio** [comment]
how can i exclude your jar?

**Comment by aemxn** [comment]
@croccio i've encountered with this error before. It seems like there is a conflict with nineoldandroids library used in your other libraries. Check one by one if other library is using it, then try to remove it.

**Comment by madcyph3r** [comment]
I will upload a release without nineoldandroid library included. Then you must include it by yourself.

**Comment by madcyph3r** [comment]
I have excluded the library in the new release, the problem must gone now. Now you must add it manually.
